# @package _global_
up_sym: False
regress_right: True
res: 4e-3
category: drawer
part_weighted: [1,1,1,1,1]
scale_range: [0.1851, 0.2381]
vote_range: [0.12, 0.12]
scale_mean: [0.07, 0.03, 0.07]
scale_mean_base: [0.64, 0.40, 0.62]  # 对于laptop的base，这个值问题很大，因为遮挡过于严重
scale_mean_child: [0.64, 0.64, 0.38]  # child 的值 比较靠谱
state: [-10,10]
lim: [0.5,0.3]