# @package _global_
up_sym: False
right_sym: False
regress_right: True
res: 1e-2
category: laptop
scale_range: [1.8, 2.3]  # 这个参数用来给训练数据进行尺度变换，以更好得适应真实场景下不同尺寸的物体
vote_range: [1.1, 1.1]  
# scale_mean_all: [0.64, 0.46, 0.44]   # 用于尺度变换的，在artimage下用不到
scale_mean_base: [0.64, 0.40, 0.62]  # 对于laptop的base，这个值问题很大，因为遮挡过于严重
scale_mean_child: [0.64, 0.64, 0.38]  # child 的值 比较靠谱
state: [-5,60]
part_weighted: [0.8,1.2,1]
lim: [0.2,0.1]
