# @package _global_
up_sym: False
right_sym: False
regress_right: True
res: 0.025
category: scissors
scale_range: [0.7, 1.3]  
vote_range: [1.2,1.2]  
scale_mean_base: [0.88, 0.0313, 0.23]  
scale_mean_child: [0.7, 0.031, 0.546]
state: [-10,10]

part_weighted: [0.9, 1.1, 1]
lim: [0.1,0.05]